version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /media/hdd/appdata/nginx:/data
      - /media/hdd/appdata/nginx/letsencrypt:/etc/letsencrypt