version: "3.7"
services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/data/autobrr/config:/config
    ports:
      - 7474:7474
