version: '2.1'
services:
    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000 - PGID=1000 - TZ=Etc/UTC
        volumes:
            - /data/media_stack/appdata/radarr:/config 
            - /data/media_stack:/data
        ports:
            - 7878:7878
        restart: unless-stopped
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /data/media_stack/appdata/sonarr:/config
            - /data/media_stack:/data
        ports:
            - 8989:8989
        restart: unless-stopped
    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /data/media_stack/appdata/jackett:/config
            - /data/media_stack/torrents:/downloads
        ports:
            - 9117:9117
        restart: unless-stopped
    deluge:
        image: lscr.io/linuxserver/deluge:latest
        container_name: deluge
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - DELUGE_LOGLEVEL=error
        volumes:
            - /data/media_stack/appdata/deluge:/config
            - /data/media_stack/torrents:/downloads
        ports:
            - 8112:8112
            - 6881:6881
            - 6881:6881/udp
            - 58846:58846
        restart: unless-stopped
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - VERSION=docker
        volumes:
            - /data/media_stack/appdata/plex:/config
            - /data/media_stack:/data
        restart: unless-stopped
    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        environment:
            - LOG_LEVEL=${LOG_LEVEL:-info}
            - LOG_HTML=${LOG_HTML:-false}
            - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
            - TZ=Europe/London
        ports:
            - 8191:8191
        restart: unless-stopped
