version: '2.1'
services:
    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        environment:
            - PUID=1000 
            - PGID=1000 
            - TZ=Etc/UTC
        volumes:
            - /mnt/data/appdata/radarr:/config 
            - /mnt/data:/data
        ports:
            - 7878:7878
        restart: unless-stopped
    sonarr:
        image: lscr.io/linuxserver/sonarr:latest
        container_name: sonarr
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /mnt/data/appdata/sonarr:/config
            - /mnt/data:/data
        ports:
            - 8989:8989
        restart: unless-stopped
    jackett:
        image: lscr.io/linuxserver/jackett:latest
        container_name: jackett
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
        volumes:
            - /mnt/data/appdata/jackett:/config
            - /mnt/data:/data
        ports:
            - 9117:9117
        restart: unless-stopped
    deluge:
        image: lscr.io/linuxserver/transmission:latest
        container_name: transmission
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - DELUGE_LOGLEVEL=error
        volumes:
            - /mnt/data/appdata/transmission:/config
            - /mnt/data/torrents:/data/torrents
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: unless-stopped
    plex:
        image: lscr.io/linuxserver/plex:latest
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Etc/UTC
            - VERSION=docker
        volumes:
            - /mnt/data/appdata/plex:/config
            - /mnt/data/media:/data/media
        restart: unless-stopped
    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        container_name: flaresolverr
        environment:
            - LOG_LEVEL=${LOG_LEVEL:-info}
            - LOG_HTML=${LOG_HTML:-false}
            - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
            - TZ=Europe/London
        ports:
            - 8191:8191
        restart: unless-stopped
