#Once up, navigate to:
#/media/hdd/appdata/plex/Library/Application Support/Plex Media Server
#Modify preferences.xml to include the following in the preferences list:
#allowedNetworks="x.x.x.x/24" for home subnet/s
version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /media/hdd/appdata/plex:/config
      - /media/hdd/data/media/:/data/media
    restart: unless-stopped