#Check log for temp password and then change it through menu
#Optionally set a whitelisted subnet to avoid auth on prem
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /media/hdd/appdata/qbittorrent:/config
      - /media/hdd/data/torrents/:/data/torrents/
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped