version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/hdd/appdata/radarr:/config
      - /media/hdd/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped